### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nathanclevenger** [drivly/sources.do#1]
- [ ] Define typescript types for Source interface
- [ ] Define simple API interface to abstract away fetch & api router, etc
- [ ] Create JSON schema for source schema
- [ ] Publish JSON schema in the schema store
- [ ] Create initial sources implementation
- [ ] Publish library as NPM package
